- README.md
Hope this is OK, let me know of any tweaks needed!
> Adds documentation on subdomain requesting, and CIDR range/country whitelisting

- .goreleaser.yml
> Testing branch dev

- .github/workflows/docker.yml
- Dockerfile
Updated github actions to build sequentially
> Updated github actions to build sequentially

- .vscode/launch.json
- .vscode/settings.json
- README.md
- channels.go
- handle.go
- main.go
- requests.go
- utils.go
Added the ability to use TCP aliases. This is a fairly crude implementation that seems to work decently well. 
Closes #35
> Added tcp alias

- .goreleaser.yml
- .vscode/launch.json
- channels.go
- handle.go
- main.go
- requests.go
- utils.go
This PR introduces fixes for #44 #42.
> Fixed starting background channels

- channels.go
- handle.go
- main.go
- requests.go
Fixed connection closing during a notty session.
> Fixed connection close during a notty session

- utils.go
> fix typo on subdomain unavailable message

- main.go
- utils.go
> Added the ability to append a user to the each subdomain

- .github/workflows/docker.yml
- .goreleaser.yml
- .vscode/launch.json
- Dockerfile
- README.md
- channels.go
- console.go
- http.go
- main.go
- requests.go
- templates/console.tmpl
- templates/footer.tmpl
- templates/header.tmpl
- templates/routes.tmpl
> Added admin features

- .github/workflows/docker.yml
- .github/workflows/lint.yml
- README.md
- main.go
- requests.go
Added keepalive and updated docker build to use cache
> Added keepalive and updated docker build to use cache

- go.mod
- go.sum
- utils.go
Change host key to ed25519 based auth
> Change host key to ed25519 based auth

- README.md
Updated documentation to be more clear for someone running through this the first time.
> Documentation update from #101

- README.md
Added documentation for basic preparation to use sish
> Added preparing DNS for wildcard to use sish

- README.md
Hey Antonio, 
thanks for the great software. During deployment I spent a long time trying to troubleshoot an error like #131. Thought of adding this in case someone bumps into the issue again.
> Clarify deployment documentation

- httpmuxer/httpmuxer.go
- utils/utils.go
Updated loader functions to support new forward params
> Updated loader functions to support new forward params

- utils/utils.go
> Moves ssh key not found errors to debug. Closes #220

- deploy/gcloud.md
Add commands for checking that the DNS records were set up correctly. Inspired by the issue https://github.com/antoniomika/sish/issues/250
> Add a sanity check to the gcloud DNS record instructions

- utils/conn.go
Set conn deadline to both reads and writes.
Thanks @bibo38 for helping verify this fix!
> Set conn deadline to both reads and writes

- go.mod
- go.sum
Update golang versions. Supersedes up #282
> Update golang versions. Supersedes up #282

- sshmuxer/aliashandler.go
> Fix typo in comment

- docs/posts/cheatsheet.md
- sshmuxer/channels.go
- sshmuxer/sshmuxer.go
- utils/conn.go
This is useful if you do not want to keep a tunnel open for an unlimited time and have Sish taking care of closing it automatically.
> Add support for setting a connection deadline
